name: CI Pipeline

on:
  push:
    branches:
      - 'feature/*'
      - 'develop'
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm test